// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rakaytqdyfhmohlxkoxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJha2F5dHFkeWZobW9obHhrb3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTY4NjMsImV4cCI6MjA2NTYzMjg2M30.uBd3QoyO64V1YfKeGyA4XSfDz4W032T-cYDA-Cim84Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);